# prometheus.yml

# Global configuration settings
global:
  scrape_interval: 15s # How often to scrape targets. 15 seconds is a good default.
  evaluation_interval: 15s # How often to evaluate rules.

# A list of scrape configurations.
scrape_configs:
  # This job scrapes metrics from the Prometheus server itself.
  # It's good practice to monitor the monitor.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # This is the crucial job for your application.
  # It tells Prometheus how to find and scrape metrics from your 'quantumq' service.
  - job_name: 'quantumq-app'
    # The path where Spring Boot Actuator exposes Prometheus metrics.
    # This matches the 'MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=prometheus' in your docker-compose.
    metrics_path: '/actuator/prometheus'
    # Docker Compose lets us use the service name 'quantumq' as the hostname.
    # Prometheus will connect to http://quantumq:8080/actuator/prometheus to get the metrics.
    static_configs:
      - targets: ['quantumq:8080']